#!/usr/bin/env bash

# A simple wrapper over zlarz for use in systemd earthquake-checker service

if "/home/$USER/bin/zlarz" -p "Mazandaran" -m 4 -l fa -n -c -e > /dev/null; then
    pw-play "/usr/share/sounds/freedesktop/stereo/suspend-error.oga"
else
    if [ "$?" -eq 3 ]; then
        exit 0
    else
        exit 1
    fi
fi
